import asyncio
import logging
from typing import Dict, Any, Optional, List
import httpx

logger = logging.getLogger("app.services.graph_agent")


class GraphAPIException(Exception):
    """Base exception for Microsoft Graph API communication."""
    pass


class GraphAPIThrottledException(GraphAPIException):
    """Raised when Microsoft Graph API throttles the client (429) and retry limit is exceeded."""
    pass


class GraphAPIRequestException(GraphAPIException):
    """Raised when an HTTP error status is returned by Microsoft Graph (e.g., 400, 401, 403, 500)."""
    
    def __init__(self, status_code: int, message: str, detail: Optional[str] = None):
        super().__init__(f"Graph API HTTP {status_code}: {message}")
        self.status_code = status_code
        self.message = message
        self.detail = detail


class GraphAPIClient:
    """
    Asynchronous client for interacting with the Microsoft Graph API.
    Handles authentication headers, request timeouts, automated pagination, and 429 Throttling retries.
    """

    BASE_URL = "https://graph.microsoft.com/v1.0"

    def __init__(
        self,
        access_token: str,
        timeout_seconds: float = 30.0,
        max_retries: int = 5,
        default_retry_sleep: float = 2.0
    ) -> None:
        """
        Initializes the Graph API Client.
        
        :param access_token: Valid OAuth 2.0 access token generated by the authentication agent.
        :param timeout_seconds: Timeout limit for connections and reading responses.
        :param max_retries: Maximum number of times to retry a request on 429 (throttling).
        :param default_retry_sleep: Default sleep time (seconds) if Retry-After header is missing.
        """
        self.access_token = access_token
        self.timeout = httpx.Timeout(timeout_seconds, connect=10.0)
        self.max_retries = max_retries
        self.default_retry_sleep = default_retry_sleep
        
        # Configure standard HTTP client headers
        self.headers = {
            "Authorization": f"Bearer {self.access_token}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        }

    async def _request_with_retry(self, method: str, url: str, **kwargs) -> httpx.Response:
        """
        Sends an HTTP request using an ephemeral httpx.AsyncClient.
        Implements transient error retries for HTTP 429 (Too Many Requests).
        """
        retry_count = 0
        
        # Ensure url is absolute
        if not url.startswith("http"):
            url = f"{self.BASE_URL}/{url.lstrip('/')}"

        while True:
            try:
                async with httpx.AsyncClient(timeout=self.timeout) as client:
                    logger.debug(f"Sending {method} request to {url}")
                    response = await client.request(method, url, headers=self.headers, **kwargs)
                
                # Check for Throttling (Too Many Requests)
                if response.status_code == 429:
                    retry_count += 1
                    if retry_count > self.max_retries:
                        raise GraphAPIThrottledException(
                            f"Graph API throttling retry limit ({self.max_retries}) exceeded for {url}."
                        )

                    # Determine wait time from "Retry-After" header
                    retry_after_str = response.headers.get("Retry-After")
                    try:
                        retry_after = float(retry_after_str) if retry_after_str else self.default_retry_sleep
                    except ValueError:
                        retry_after = self.default_retry_sleep

                    logger.warning(
                        f"Microsoft Graph Throttling (429) received. "
                        f"Retry-After={retry_after}s. Attempt {retry_count}/{self.max_retries}."
                    )
                    await asyncio.sleep(retry_after)
                    continue

                # Raise for other error status codes (4xx, 5xx)
                if response.is_error:
                    # Attempt to extract Microsoft Graph error detail
                    error_json = {}
                    try:
                        error_json = response.json().get("error", {})
                    except Exception:
                        pass
                    
                    err_msg = error_json.get("message", response.text)
                    err_code = error_json.get("code", "Unknown")
                    raise GraphAPIRequestException(
                        status_code=response.status_code,
                        message=err_msg,
                        detail=err_code
                    )

                return response

            except httpx.RequestError as e:
                # Handle connection errors, network hiccups, etc.
                retry_count += 1
                if retry_count > self.max_retries:
                    raise GraphAPIException(f"Network error during request: {e}")
                
                # Exponential backoff for connection retries
                sleep_time = self.default_retry_sleep * (2 ** (retry_count - 1))
                logger.warning(f"Network error: {e}. Retrying in {sleep_time}s...")
                await asyncio.sleep(sleep_time)

    async def get_resource(self, endpoint: str) -> Dict[str, Any]:
        """
        Asynchronously fetches a resource from Microsoft Graph API (HTTP GET).
        Automatically aggregates paginated collections using the `@odata.nextLink` property.
        
        :param endpoint: Graph API endpoint relative path (e.g. "deviceManagement/deviceConfigurations")
                         or a full URL.
        :return: Decoded JSON response dictionary. If paginated, the dict's "value" field will
                 contain the full merged list of all pages.
        """
        # 1. Fetch the first page
        response = await self._request_with_retry("GET", endpoint)
        data = response.json()

        # 2. Check if this is a paginated collection response
        if isinstance(data, dict) and "value" in data and isinstance(data["value"], list):
            aggregated_list: List[Any] = data["value"]
            next_link = data.get("@odata.nextLink")

            # 3. Follow pagination loop
            while next_link:
                logger.debug(f"Following @odata.nextLink: {next_link}")
                next_response = await self._request_with_retry("GET", next_link)
                next_data = next_response.json()

                if isinstance(next_data, dict) and "value" in next_data and isinstance(next_data["value"], list):
                    aggregated_list.extend(next_data["value"])
                
                # Fetch next pointer if exists
                next_link = next_data.get("@odata.nextLink")

            # Store the consolidated list back in the dictionary
            data["value"] = aggregated_list

        return data

    async def post_resource(self, endpoint: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        Asynchronously creates/updates a resource in Microsoft Graph API (HTTP POST).
        
        :param endpoint: Graph API endpoint path.
        :param payload: JSON body dictionary to post.
        :return: Decoded JSON response from Microsoft Graph.
        """
        response = await self._request_with_retry("POST", endpoint, json=payload)
        
        # Graph might return 204 No Content for successful posts without response body
        if response.status_code == 204 or not response.text:
            return {}
            
        try:
            return response.json()
        except ValueError:
            return {"raw_response": response.text}

    async def enrich_policy_payload(self, endpoint: str, policy: Dict[str, Any]) -> None:
        """
        Enriches a policy dictionary with its sub-resources if the Microsoft Graph API 
        list endpoint omits them. Modifies the policy dict in-place.
        """
        policy_id = policy.get("id")
        if not policy_id:
            return
            
        endpoint_lower = endpoint.lower()
        
        # 1. Settings Catalog
        if "devicemanagement/configurationpolicies" in endpoint_lower:
            try:
                settings_data = await self.get_resource(f"deviceManagement/configurationPolicies/{policy_id}/settings")
                if isinstance(settings_data, dict) and "value" in settings_data:
                    policy["settings"] = settings_data["value"]
            except Exception as e:
                logger.warning(f"Failed to fetch settings for configuration policy {policy_id}: {e}")
                
        # 2. ADMX Group Policy Configurations
        elif "devicemanagement/grouppolicyconfigurations" in endpoint_lower:
            try:
                def_values_data = await self.get_resource(f"deviceManagement/groupPolicyConfigurations/{policy_id}/definitionValues?$expand=definition")
                if isinstance(def_values_data, dict) and "value" in def_values_data:
                    policy["definitionValues"] = def_values_data["value"]
            except Exception as e:
                logger.warning(f"Failed to fetch definitionValues for ADMX policy {policy_id}: {e}")
                
        # 3. Compliance Policies Scheduled Actions
        elif "devicemanagement/devicecompliancepolicies" in endpoint_lower:
            try:
                actions_data = await self.get_resource(f"deviceManagement/deviceCompliancePolicies/{policy_id}/scheduledActionsForRule?$expand=scheduledActionConfigurations")
                if isinstance(actions_data, dict) and "value" in actions_data:
                    policy["scheduledActionsForRule"] = actions_data["value"]
            except Exception as e:
                logger.warning(f"Failed to fetch scheduled actions for compliance policy {policy_id}: {e}")
